#ifndef packet_h
#define packet_h

#ifndef OSXRDP_PACKETTYPE
#define OSXRDP_PACKETTYPE

#define OSXRDP_RECORDFORMAT_BGRA32 0
#define OSXRDP_RECORDFORMAT_NV12   1

#define OSXRDP_CMDTYPE_SCREEN 1
#define OSXRDP_PACKETTYPE_REQ_SCREEN 1
#define OSXRDP_PACKETTYPE_REP_SCREEN 2
#define OSXRDP_PACKETTYPE_REQ_SCREENOFF 3
#define OSXRDP_PACKETTYPE_REP_SCREENOFF 4
#define OSXRDP_PACKETTYPE_MOUSEEVT      5
#define OSXRDP_PACKETTYPE_KEYBOARDEVT   6

#define OSXRDP_CMDTYPE_DUMMY 2

#define OSXRDP_CMDTYPE_MSGFROMAGENT 3
#define OSXRDP_PACKETTYPE_TERMINATE 1


#endif

#ifndef XRDP_KEYBOARD_EVT
#define XRDP_KEYBOARD_EVT

#define XRDP_KEYBOARD_DOWN  15
#define XRDP_KEYBOARD_UP    16

#endif


#ifndef XRDP_MOUSE_EVT
#define XRDP_MOUSE_EVT

#define XRDP_MOUSE_MOVE         100
#define XRDP_MOUSE_LBTNUP       101
#define XRDP_MOUSE_LBTNDOWN     102
#define XRDP_MOUSE_RBTNUP       103
#define XRDP_MOUSE_RBTNDOWN     104
#define XRDP_MOUSE_MBTNUP       105
#define XRDP_MOUSE_MBTNDOWN     106
#define XRDP_MOUSE_WHEELUP      107
#define XRDP_MOUSE_WHEELDOWN    109
#define XRDP_MOUSE_BBTNUP       115 // 마우스 뒤로가기키 (측면)
#define XRDP_MOUSE_BBTNDOWN     116
#define XRDP_MOUSE_FBTNUP       117 // 마우스 앞으로가기키 (측면)
#define XRDP_MOUSE_FBTNDOWN     118

#endif



#endif /* packet_h */
