#!/bin/bash

# generate key
/Applications/osxrdp/OSXRDP.app/Contents/MacOS/xrdp-keygen xrdp auto

# create log file
touch /var/log/xrdp.log

# start service
launchctl bootstrap system /Library/LaunchDaemons/com.byungho.osxrdp.plist
launchctl enable system/com.byungho.osxrdp
launchctl kickstart -k system/com.byungho.osxrdp

launchctl bootstrap system /Library/LaunchDaemons/com.byungho.osxrdp.sessionmanager.plist
launchctl enable system/com.byungho.osxrdp.sessionmanager
launchctl kickstart -k system/com.byungho.osxrdp.sessionmanager

launchctl load /Library/LaunchAgents/com.byungho.osxrdp.lockscreen.plist
