#!/bin/bash

# generate key (classic rdp)
/Applications/osxrdp/OSXRDP.app/Contents/MacOS/xrdp-keygen xrdp auto

# generate tls key
/usr/bin/openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout /etc/xrdp/key.pem \
    -out  /etc/xrdp/cert.pem \
    -days 3650 -subj "/CN=osxrdp"

# create log file (xrdp)
touch /var/log/xrdp.log

# create log folder (osxrdp)
mkdir -p /Library/Logs/osxrdp
chmod 755 /Library/Logs/osxrdp

# start service
launchctl bootstrap system /Library/LaunchDaemons/com.byungho.osxrdp.plist
launchctl enable system/com.byungho.osxrdp
launchctl kickstart -k system/com.byungho.osxrdp

launchctl bootstrap system /Library/LaunchDaemons/com.byungho.osxrdp.sessionmanager.plist
launchctl enable system/com.byungho.osxrdp.sessionmanager
launchctl kickstart -k system/com.byungho.osxrdp.sessionmanager

launchctl load /Library/LaunchAgents/com.byungho.osxrdp.lockscreen.plist
