#!/bin/bash

# generated by AI

# ==========================================
# 설정 변수
# ==========================================
APP_NAME="OSXRDP.app"
UNINS_APP_NAME="OSXRDPUninstaller.app"
INSTALL_FOLDER_NAME="osxrdp"
PKG_ID="com.byungho.osxrdp.setup"
VERSION="1.4.0"

# 파일명 설정
COMPONENT_PKG="osxrdp_component.pkg"
OUTPUT_PKG="osxrdp_installer_v${VERSION}.pkg"
DIST_XML="distribution.xml"

# 경로 설정
ROOT_DIR=$(pwd)
PAYLOAD_DIR="$ROOT_DIR/payload"
SOURCE_DIR="$ROOT_DIR/source"
SCRIPTS_DIR="$ROOT_DIR/scripts"

# [추가됨] 서명 및 공증 설정
# 터미널에서 'security find-identity -v -p installer' 로 확인한 이름 ("Developer ID Installer: Name (TeamID)")
SIGNING_IDENTITY="Developer ID Installer: BYEONGHO KIM (33X7M69J4B)"

# 터미널에서 'xcrun notarytool store-credentials' 명령어로 생성한 프로필 이름
NOTARY_KEYCHAIN_PROFILE="AC_PASSWORD"

# ==========================================
# 0. 사전 체크
# ==========================================
if [ ! -f "$DIST_XML" ]; then
    echo "❌ Error: $DIST_XML not found in current directory."
    exit 1
fi

echo "=== [1/6] Cleaning up old build files ==="
rm -rf "$PAYLOAD_DIR"
rm -f "$COMPONENT_PKG" "$OUTPUT_PKG"

# ==========================================
# 1. Payload 구성
# ==========================================
echo "=== [2/6] Staging files into Payload ==="

mkdir -p "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME"
mkdir -p "$PAYLOAD_DIR/Library/LaunchDaemons"
mkdir -p "$PAYLOAD_DIR/etc/xrdp"
mkdir -p "$PAYLOAD_DIR/usr/local/lib/xrdp"
mkdir -p "$PAYLOAD_DIR/usr/local/share/xrdp"

# 앱 복사 (이미 서명된 앱이라고 가정)
if [ -d "$SOURCE_DIR/$APP_NAME" ]; then
    cp -R "$SOURCE_DIR/$APP_NAME" "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME/"
else
    echo "❌ Error: '$APP_NAME' not found in source directory."
    exit 1
fi

if [ -d "$SOURCE_DIR/$UNINS_APP_NAME" ]; then
    cp -R "$SOURCE_DIR/$UNINS_APP_NAME" "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME/"
else
    echo "❌ Error: '$UNINS_APP_NAME' not found in source directory."
    exit 1
fi
# 기타 파일 복사
cp "$SOURCE_DIR/com.byungho.osxrdp.plist" "$PAYLOAD_DIR/Library/LaunchDaemons/"
if [ -d "$SOURCE_DIR/config" ]; then
    cp -R "$SOURCE_DIR/config/"* "$PAYLOAD_DIR/etc/xrdp/"
fi
cp "$SOURCE_DIR/module/libosxup.dylib" "$PAYLOAD_DIR/usr/local/lib/xrdp"
cp "$SOURCE_DIR/resources/"* "$PAYLOAD_DIR/usr/local/share/xrdp"

# 권한 설정
echo "=== [3/6] Setting permissions ==="
sudo chown -R root:wheel "$PAYLOAD_DIR"
sudo chmod 755 "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME"
sudo chmod 755 "$PAYLOAD_DIR/usr/local/lib/xrdp"
sudo chmod 755 "$PAYLOAD_DIR/usr/local/share/xrdp"
sudo chmod 755 "$SCRIPTS_DIR/postinstall"

# ==========================================
# 2. 컴포넌트 패키지 빌드 (pkgbuild)
# ==========================================
echo "=== [4/6] Building Component Package ==="

pkgbuild --root "$PAYLOAD_DIR" \
         --install-location "/" \
         --scripts "$SCRIPTS_DIR" \
         --identifier "$PKG_ID" \
         --version "$VERSION" \
         "$COMPONENT_PKG"

# ==========================================
# 3. 최종 Product 패키지 빌드 및 서명 (productbuild)
# ==========================================
echo "=== [5/6] Building & Signing Product Package ==="

# --sign 옵션을 사용하여 빌드와 동시에 서명을 수행합니다.
productbuild --distribution "$DIST_XML" \
             --package-path . \
             --sign "$SIGNING_IDENTITY" \
             "$OUTPUT_PKG"

if [ $? -ne 0 ]; then
    echo "❌ Error: Product build or signing failed."
    exit 1
fi

# ==========================================
# 4. 공증 (Notarization) 및 Stapling
# ==========================================
echo "=== [6/6] Notarizing Package ==="

echo "📤 Uploading to Apple Notary Service... (This may take a while)"
xcrun notarytool submit "$OUTPUT_PKG" \
                 --keychain-profile "$NOTARY_KEYCHAIN_PROFILE" \
                 --wait

if [ $? -eq 0 ]; then
    echo "✅ Notarization Succeeded!"
    
    echo "📎 Stapling the ticket to the package..."
    xcrun stapler staple "$OUTPUT_PKG"
    
    echo "🎉 All Done! Final Package: $OUTPUT_PKG"
else
    echo "❌ Notarization Failed. Check the log above."
    exit 1
fi

# 임시 파일 정리
rm -f "$COMPONENT_PKG"
sudo rm -rf "$PAYLOAD_DIR"
