//
//  CJKHelper.h
//  OSXRDP
//
//  Created by byungho on 5/16/26.
//

// idea from kawa https://github.com/hatashiro/kawa/pull/12
// codes generated by AI

#import <Foundation/Foundation.h>
#import <Carbon/Carbon.h>

NS_ASSUME_NONNULL_BEGIN

@interface CJKHelper : NSObject

+ (OSStatus)selectNextInputSourceWithWorkaround;

@end

NS_ASSUME_NONNULL_END
